name       : soapysdr
version    : 0.7.0
release    : 2
source     :
    - https://github.com/pothosware/SoapySDR/archive/soapy-sdr-0.7.0.tar.gz : cb2344be77f4d04f6cbafa183c7e39a2e6eb0da39c98fa77e9d60686c4e81e52
license    : BSL-1.0
component  : programming.library
summary    : Software defined radio interface library
description: |
    SoapySDR is a library providing a common interface to SDR (software
    defined radio) hardware. Support for different hardware is added through
    external modules.
builddeps  :
    - pkgconfig(python3)
    - swig
setup      : |
    %cmake . -DLIB_SUFFIX=64
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
