name       : soapysdr
version    : 0.6.1
release    : 1
source     :
    - https://github.com/pothosware/SoapySDR/archive/soapy-sdr-0.6.1.tar.gz : 2ecf8e43518dfb24bd172923adf6ce25a6d3e39de3a8aadf26c890f60dd1e9f7
license    : BSL-1.0
component  : programming.library
summary    : Software defined radio interface library
description: |
    SoapySDR is a library providing a common interface to SDR (software
    defined radio) hardware. Support for different hardware is added through
    external modules.
builddeps  :
    - pkgconfig(python3)
    - swig
setup      : |
    %cmake . -DLIB_SUFFIX=64
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
