name       : soapysdr
version    : 0.7.2
release    : 5
source     :
    - https://github.com/pothosware/SoapySDR/archive/refs/tags/soapy-sdr-0.7.2.tar.gz : 6eb4143fed115911884bdbbe6fe32dbd99b4ada210c9e126ac3c49c24414347a
license    : BSL-1.0
component  : programming.library
summary    : Software defined radio interface library
description: |
    SoapySDR is a library providing a common interface to SDR (software
    defined radio) hardware. Support for different hardware is added through
    external modules.
builddeps  :
    - pkgconfig(python3)
    - swig
setup      : |
    %cmake . -DLIB_SUFFIX=64
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
